from __future__ import annotations

from dataclasses import dataclass

from nps.symbols.symbol_dictionary import SymbolDictionary


@dataclass(frozen=True)
class SymbolSnapshotRow:
    name: str
    kind: str
    domain: str
    codomain: str
    regularity: str
    locality: str
    source: str


def render_symbol_dictionary_markdown(symbols: SymbolDictionary) -> str:
    """Render a deterministic markdown snapshot of the current SymbolDictionary."""

    version = symbols.frozen_version if symbols.is_frozen() else "UNFROZEN"

    entries = sorted(symbols.entries(), key=lambda e: e.name)
    rows: list[SymbolSnapshotRow] = []
    for entry in entries:
        obj = entry.obj
        rows.append(
            SymbolSnapshotRow(
                name=entry.name,
                kind="MathematicalObject",
                domain=obj.domain,
                codomain=obj.codomain,
                regularity=str(obj.regularity.value),
                locality=str(obj.locality.value),
                source=f"{obj.source.key}: {obj.source.detail}",
            )
        )

    header = (
        "# CAS-A Symbol Dictionary Snapshot\n\n"
        "This file is a deterministic snapshot generated by `render_symbol_dictionary_markdown`.\n\n"
        f"Freeze version: {version}\n\n"
        "| name | kind | domain | codomain | regularity | locality | source |\n"
        "|---|---|---|---|---|---|---|\n"
    )

    body_lines: list[str] = []
    for row in rows:
        body_lines.append(
            "| "
            + " | ".join(
                [
                    row.name,
                    row.kind,
                    row.domain,
                    row.codomain,
                    row.regularity,
                    row.locality,
                    row.source,
                ]
            )
            + " |"
        )

    return header + "\n".join(body_lines) + "\n"
